SRCH-3293 Make ElasticSearch 7 the default for development and testing
GSA/search-gov pull request #1077
Opened 2022-12-22 20:07 UTC by ddzz

## Summary
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [ ] You have specified at least one "Reviewer".

2022-12-27 15:47 UTC, MyNameIsMissing requested changes
Could you change the version to 7.17.7 from 7.17.3?  ES 7 is still a live version and will change, but for now we have 7.17.7 in Prod and that's what I'm putting in Staging.

2023-01-04 16:48 UTC, MyNameIsMissing submitted a review, later dismissed
LGTM

The item I was wondering about is just in the readme line 38, so can stay as is since it's just an example of the expected response

2023-01-05 00:37 UTC, ddzz commented
@MyNameIsMissing can you approve this PR again? I ended up updating the README to keep the versions consistent.

2023-01-05 15:01 UTC, MyNameIsMissing approved these changes
LGTM

2023-01-06 16:56 UTC, merged