SRCH-3617 Site_limits filtering in Results API
GSA/search-gov pull request #1079
Opened 2022-12-29 16:52 UTC by lorawoodford

## Summary
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [ ] You have specified at least one "Reviewer".

2022-12-30 18:45 UTC, MothOnMars requested changes
This looks like slightly more code than we need, as I14y searches already support the `sitelimit` parameter with one or more domains or paths. I don't think we want to use two different parameters for the same thing: `sitelimit` in the browser, vs. `site_limits` for API searches. 

I played around with this a bit, and it appears that all we need to do to support a `sitelimit` parameter in the API is to permit the param and change its key to `site_limits` in the search options (which is somewhat annoying, but mirrors what we do for browser-based searches: https://github.com/GSA/search-gov/blob/main/app/controllers/application_controller.rb#L93. It would be nice, but not required, if we could eventually DRY up the search params code between the app controller and the API controller.)

This is my POC branch with the minimal set of changes required to support the `sitelimit` param in the API (not prescriptive code, just a working example):
https://github.com/GSA/search-gov/compare/main...MothOnMars:SRCH-3617-mct-new?expand=1

It ensures that a search with params such as `query=sitemap&sitelimit=search.gov/indexing+search.gov/about` returns the same results via the browser or the search API. 

It would also help to have an integration spec for this behavior, probably in `spec/requests/api/v2/search_spec.rb`. 

Note that neither approach will support sites using indexed documents instead of I14y. I assume we'll call that out on the updated API documentation. It may also makes sense to use different search options validators for `blended` vs `i14y` api searches:
```
# current
when :blended, :i14y, :video then Api::NonCommercialSearchOptions
```
With the faceted search work, we probably shouldn't continue to use the same options for all those search classes, as they won't all work consistently. @amanifarooque, can you chime in on the expected behavior for sites using the results API with indexed documents? Do we need a follow-up story to either support that or to inform those users that the `sitelimit` param isn't supported for those searches?

To summarize the requested changes at this point in time:
- make the necessary changes to support the `sitelimit` parameter instead of the `site_limits` parameter for API users with i14y content
- add an integration spec for that behavior
- back out any unnecessary changes from the search models

2023-01-04 14:18 UTC, amanifarooque commented
Re the below comment:

> With the faceted search work, we probably shouldn't continue to use the same options for all those search classes, as they won't all work consistently. @amanifarooque, can you chime in on the expected behavior for sites using the results API with indexed documents? Do we need a follow-up story to either support that or to inform those users that the sitelimit param isn't supported for those searches?

There is no expectation to support this behavior for blended search / ODIE powered sites. The use case for results API users hitting that endpoint is pretty low. We have some items to update results API documentation, we can make all the changes to the various places wholesale after the bulk of API updates are completed.

2023-01-06 16:06 UTC, lorawoodford commented
@MothOnMars This should be ready for re-review.  It may still look like a lot of changes, but that's just because I've not backed out the rubocop-only changes introduced in the earlier draft, though it _does_ back out all the meaningful/impactful code changes initially made in those files.

2023-01-06 18:34 UTC, MothOnMars commented on spec/controllers/api/v2/searches_controller_spec.rb
> +          expect(ApiI14ySearch).to have_received(:new).with(hash_including(site_limits: 'nps.gov'))
OK to leave these as-is, but we could also include some line breaks for readability:
```ruby
expect(ApiI14ySearch).to have_received(:new).
  with(hash_including(site_limits: 'nps.gov'))
```

2023-01-06 18:39 UTC, MothOnMars submitted a review, later dismissed
LGTM

2023-01-06 21:22 UTC, lorawoodford commented
@MothOnMars I added the line breaks to the spec, so one more approval needed.

2023-01-06 21:39 UTC, MothOnMars approved these changes
Lookin' good!

2023-01-09 16:18 UTC, merged