SRCH-3929 Redact PII from request params in logs
GSA/search-gov pull request #1159
Opened 2023-03-20 19:22 UTC by lorawoodford

## Summary
- Two additions to `filtered_parameter_logging` to ensure potentially sensitive queries do not end up in our searchgov logs:
 - Fully filters the `q` param to ensure sayt searches don't divulge sensitive information;
 - Runs the values of the `query` parameters through `Redactor.redact` to ensure potentially sensitive strings (and _only_ potentially sensitive strings) are redacted
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [x] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

2023-03-21 14:06 UTC, MothOnMars requested changes
See https://github.com/GSA/asis/pull/192#pullrequestreview-1350487380

2023-03-21 16:42 UTC, lorawoodford commented on spec/config/initializers/filter_parameter_logging_spec.rb
> +    expect(parameter_filter.filter({ 'query' => 'safe query' })).to eq({ 'query' => 'safe query' })
Done.

2023-03-21 16:48 UTC, MothOnMars commented
@lorawoodford , I'll go ahead and approve this, but this is the spec I had been thinking of:
https://github.com/gsa/search-gov/commit/b7aae0839cf5f1815e3a8d4b8e5eb2d768f729a9#diff-67ddf299fbe73b923c9ada5eddb74fbb7a912418dfd1b8362d6bd3126cec71edR19

That was written when we were on Rails 4.2, and removed when we integrated Login.gov, so it's possible a similar spec might be trickier. I also don't love using controller specs, but we have plenty already in search-gov.

2023-03-21 16:50 UTC, MothOnMars commented on spec/config/initializers/filter_parameter_logging_spec.rb
> +    expect(parameter_filter.filter({ 'query' => 'safe query' })).to eq({ 'query' => 'safe query' })
The curly brackets are not needed, but otherwise LTGM

2023-03-21 16:50 UTC, MothOnMars submitted a review, later dismissed

2023-03-21 16:56 UTC, lorawoodford commented on spec/config/initializers/filter_parameter_logging_spec.rb
> +    expect(parameter_filter.filter({ 'query' => 'safe query' })).to eq({ 'query' => 'safe query' })
Sorry!  Was moving too fast before breaking for lunch!  Didn't meant to ignore that recommendation!

2023-03-22 14:02 UTC, lorawoodford commented
@MothOnMars I removed the curly braces, so could use one more approval.  Sorry!

2023-03-22 14:04 UTC, MothOnMars approved these changes
LGTM (although there are still curly brackets in the `does not redact non-sensitive queries` spec :) )

2023-03-22 14:07 UTC, lorawoodford commented
@MothOnMars Gah!  Sorry... once more.  That would have annoyed me if I left it.

2023-03-22 14:09 UTC, MothOnMars approved these changes
LGTM, pending CI

2023-03-22 18:55 UTC, merged