SRCH-3647: health topic integration
GSA/search-gov pull request #1310
Opened 2023-09-29 17:10 UTC by yogesh27

## Summary
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [ ] You have specified at least one "Reviewer".

2023-10-03 21:12 UTC, stevenbarragan submitted a review, later dismissed
LGTM

2023-10-05 17:22 UTC, stevenbarragan requested changes
One minor thing I didn't catch last time and we should be good to go

2023-10-05 17:22 UTC, stevenbarragan commented on app/javascript/components/Results/Results.tsx
>            {/* Health topics - To Do as part of backend integration */}
We should remove this comments. I don't think they're needed any more? right?

2023-10-05 17:29 UTC, yogesh27 commented
> One minor thing I didn't catch last time and we should be good to go

good catch

2023-10-05 17:47 UTC, stevenbarragan requested changes

2023-10-05 17:47 UTC, stevenbarragan commented on app/javascript/components/Results/Results.tsx
>            {/* <HealthTopics /> */}
Same comment as last time. This should be removed

2023-10-05 17:52 UTC, stevenbarragan submitted a review, later dismissed
LGTM 👍🏽

2023-10-05 21:48 UTC, stevenbarragan approved these changes
LGTM

2023-10-05 22:24 UTC, merged