SRCH-4446 Integrate footer links
GSA/search-gov pull request #1329
Opened 2023-10-24 14:48 UTC by lorawoodford

## Summary
- Integrates the footer links settings in the Admin Center into the redesigned SERP;
- Also, per the discussion and updated AC in the story, `addressItems` placeholder content has been removed.
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [x] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

2023-10-26 20:24 UTC, stevenbarragan requested changes
Looks good but remove the double sorting please.

2023-10-26 20:24 UTC, stevenbarragan commented on app/helpers/react_helper.rb
> +  # rubocop:disable Metrics/AbcSize
I guess it's fine right here since all this will be API driven in the future 🤞🏽 , no need to do a refactor of this right now.

2023-10-27 12:49 UTC, lorawoodford commented on app/helpers/react_helper.rb
> +    links.sort_by(&:position).map do |link|
Thanks, done.

2023-10-27 15:35 UTC, stevenbarragan approved these changes

2023-10-27 18:25 UTC, merged