SRCH-3996 videos page integration
GSA/search-gov pull request #1339
Opened 2023-11-01 21:05 UTC by yogesh27

## Summary
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [ ] You have specified at least one "Reviewer".

2023-11-02 15:29 UTC, stevenbarragan submitted a review, later dismissed
LGTM

2023-11-03 15:40 UTC, stevenbarragan requested changes
Please fix typo

2023-11-03 15:40 UTC, stevenbarragan commented on app/javascript/test/Video.test.tsx
> +  it('shows vidoe image and title', () => {
typo `vidoe` => `video`

2023-11-03 15:49 UTC, yogesh27 commented on app/javascript/test/Video.test.tsx
> +  it('shows vidoe image and title', () => {
this has been fixed

2023-11-03 15:50 UTC, stevenbarragan approved these changes

2023-11-06 17:20 UTC, merged