SRCH-5350 Vote.gov link backend setup
GSA/search-gov pull request #1627
Opened 2024-08-07 16:14 UTC by krbhavith

## Summary
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [ ] You have specified at least one "Reviewer".

2024-08-12 21:50 UTC, stevenbarragan requested changes
Plase use environment variables for settings instead of secrets form now on.

2024-08-12 21:50 UTC, stevenbarragan commented on app/helpers/react_helper.rb
> +      showVoteOrgLink: affiliate.show_vote_org_link && Rails.application.secrets[:enable_vote_org_link],
We're moving away from secrets. As it says in the ticket, we need to use the `ENABLE_VOTE_ORG_LINK` environment variable instead.

2024-08-13 16:14 UTC, stevenbarragan requested changes
Please remove the dotenv changes but keep using an environment variable. Dotenv will be setup slightly different.

2024-08-13 17:31 UTC, krbhavith commented
> Please remove the dotenv changes but keep using an environment variable. Dotenv will be setup slightly different.

@stevenbarragan reverted dotenv gem changes and updated with environment variable

2024-08-13 20:31 UTC, stevenbarragan approved these changes

2024-08-13 20:32 UTC, merged