SRCH-4962 Upgrade ruby version for search-gov to 3.3
GSA/search-gov pull request #1629
Opened 2024-08-15 17:15 UTC by krbhavith

## Summary
- Upgrade ruby to 3.3 for search-gov
- Resolve deprecations
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [ ] You have specified at least one "Reviewer".

2024-08-21 18:09 UTC, stevenbarragan requested changes
There are a few things that still need to be addressed.

2024-08-22 19:18 UTC, krbhavith commented on lib/es.rb
> +      Rails.application.config.secret_keys.dig(:analytics, :elasticsearch, mode).freeze
@luisgmetzger do we always have multiple `writers` in elasticsearch configuration. Thinking how to refactor the file based on the above comment

2024-08-27 19:17 UTC, stevenbarragan approved these changes
LGTM

2024-08-27 20:12 UTC, stevenbarragan approved these changes
:shipit:

2024-08-27 20:32 UTC, stevenbarragan approved these changes
🚀

2024-08-27 21:33 UTC, stevenbarragan approved these changes
:shipit:

2024-08-27 21:34 UTC, merged