Tweaks to RuboCop settings file.
GSA/search-gov pull request #640
Opened 2020-12-09 19:37 UTC by jmax-fearless

- Weakened indentation requirements for multi-method
  chaining (e.g. fluent interfaces). Rubocop's strong style for this is
  not the team's preference.

- Turned off block length cop for selected RSpec blocks.

- Turned off Rspec cops for example length and block nesting depth.

2020-12-09 19:51 UTC, MothOnMars requested changes
one tweak

2020-12-09 19:51 UTC, MothOnMars commented on .rubocop.yml
> +
remove extra line break

2020-12-10 14:14 UTC, MothOnMars approved these changes
LGTM. I will approve the CC failures.

2020-12-10 15:35 UTC, jmax-fearless commented
Created SRCH-1781 to track this change through the process.

2020-12-10 15:42 UTC, MothOnMars commented
When merging, be sure to add the JIRA # to the commit message

2020-12-10 16:23 UTC, merged