SRCH-2860: remove the AgencyQuery table, code, etc.
GSA/search-gov pull request #930
Opened 2022-05-12 23:10 UTC by jamesmadhoc

## Summary
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review:

#### Functionality Checks

- [x] Code is functional.

- [x] Automated checks pass, if applicable. If Code Climate checks do not pass, explain reason for failures:

- [x] If your changes will be tested manually, you have run `bundle update` and committed your changes to Gemfile.lock.
 
- [x] You have merged the latest changes from the target branch (usually `master` or `main`) into your branch.
 
- [x] If your target branch is NOT `master` or `main`, specify the reason:
 
- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release #.#.#** matching the release number
 
- [x] You have squashed your commits into a single commit (exception: your PR includes commits with formatting-only changes, such as required by Rubocop)

- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket
 
#### Process Checks

- [ ] You have specified an "Assignee", and if necessary, additional reviewers

2022-05-16 14:45 UTC, MothOnMars requested changes

2022-05-16 18:28 UTC, jamesmadhoc commented on db/migrate/20220512200543_drop_agency_queries.rb
> +    raise ActiveRecord::IrreversibleMigration, "Cannot restore dropped agency_queries table."
Updated the migration to have a "down" method that recreates the agency_queries table; rolled back the migration locally and it re-created the table in the DB and in db/schema.rb; ran it forward again and it dropped the table in both places (would this constitute a manual acceptance test?).  The rubocop complaint about spec/controllers/admin/fabricated_coverage_for_active_scaffold_controllers_spec.rb remains, of course.  One last question:  should the "down" method include a warning about manual reconstitution of the data in the agency_queries table?

2022-05-17 14:41 UTC, MothOnMars approved these changes
LGTM. 

Just noting for posterity that if we did need to roll back the migration, it would result in some changes to the field settings, and a new index on `agency_id`:
```diff
-  create_table "agency_queries", id: :integer, charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
+  create_table "agency_queries", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
     t.string "phrase"
-    t.integer "agency_id"
-    t.datetime "created_at"
-    t.datetime "updated_at"
+    t.bigint "agency_id"
+    t.datetime "created_at", precision: 6, null: false
+    t.datetime "updated_at", precision: 6, null: false
+    t.index ["agency_id"], name: "index_agency_queries_on_agency_id"
     t.index ["phrase"], name: "index_agency_queries_on_phrase", unique: true
   end
   ```
The differences appear to be the result of new defaults applied by Rails migration methods. I'm not too worried about having to roll back this change, but it's something we'd have to consider if we were dropping a riskier table. It would also be safer to drop the table in a follow-up commit after the code changes are deployed.

2022-05-17 17:52 UTC, MothOnMars commented on db/migrate/20220512200543_drop_agency_queries.rb
> +    raise ActiveRecord::IrreversibleMigration, "Cannot restore dropped agency_queries table."
I don't think we need to worry about a warning; if we needed to roll back, I have faith in us to remember we'd need to replace the data. 

Re. Rubocop, I've approved the offense in Code Climate as pre-existing.

2022-05-23 20:22 UTC, merged