SRCH-3046 Update README with standardized search-services language
GSA/search-gov pull request #942
Opened 2022-06-17 16:11 UTC by danswick

related: https://github.com/GSA/i14y/pull/193, https://github.com/GSA/search-services/pull/5

## Summary
 Updates README language to direct users to search-services for more information on setting up and running shared services.

### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review:

#### Functionality Checks

- [x] Code is functional.

- [x] Automated checks pass, if applicable. If Code Climate checks do not pass, explain reason for failures: **N/A**: checks don't apply to README.

- [x] If your changes will be tested manually, you have run `bundle update` and committed your changes to Gemfile.lock. **N/A**: no manual tests required for README updates.
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
 
- [x] If your target branch is NOT `main`, specify the reason:
 
- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release #.#.#** matching the release number
 
- [x] You have squashed your commits into a single commit (exception: your PR includes commits with formatting-only changes, such as required by Rubocop)

- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket. **N/A**: I plan to use "squash and merge" instead of a manual squash.
 
#### Process Checks

- [x] You have specified an "Assignee", and if necessary, additional reviewers

2022-06-28 16:26 UTC, danswick commented
@MothOnMars PR checklist has been updated!

2022-07-01 18:50 UTC, lorawoodford requested changes
@danswick One tiny typo change/clarification!

2022-07-01 18:50 UTC, lorawoodford commented on README.md
> +Verify that Elasticsearch 6.8.x is running on port the expected port (in this example, port 9200):
```suggestion
Verify that Elasticsearch 6.8.x is running on the expected port (port 9200 by default):
```

2022-07-05 15:50 UTC, lorawoodford approved these changes
LGTM

2022-07-05 18:53 UTC, merged