SRCH-3206 Update attribute serialization and undo yaml unsafe load
GSA/search-gov pull request #979
Opened 2022-08-08 20:40 UTC by lorawoodford

## Summary
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks

- [ ] You have run `bundle update` and committed your changes to Gemfile.lock.
 
- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
 
- [ ] You have squashed your commits into a single commit (exceptions: your PR includes commits with formatting-only changes, such as required by Rubocop or Cookstyle, or if this is a feature branch that includes multiple commits).
 
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [ ] You have specified at least one "Reviewer".

2022-08-09 17:26 UTC, MothOnMars commented on Gemfile
> +gem 'curb', '~> 1.0', '>= 1.0.1'
Let's just use: `'~> 1.0.1'`. I don't trust `curb` enough to bump minor versions with a `bundle update`. Eventually I would like to remove `curb` entirely in favor of either `faraday` or `http`.

2022-08-09 17:30 UTC, MothOnMars requested changes
Per our discussion, we will simplify this code by:
- removing the new gem
- backing out the db changes
- using ActiveRecord::Store

POC of the simplified changeset:
https://github.com/GSA/search-gov/compare/main...MothOnMars:unsafe_3206?expand=1

We'll also add comments alongside the `store` methods indicating that in the future, we may want to change the db column type to `json`.

2022-08-09 20:22 UTC, lorawoodford commented
@MothOnMars Changes made.  Please re-review when able.  Thanks!

2022-08-10 16:40 UTC, MothOnMars requested changes
Code looks good. Just need to tweak some of Rubocop's autocorrections.

2022-08-10 16:40 UTC, MothOnMars commented on spec/lib/importers/rss_feed_data_spec.rb
> +      it 'populates and index just the news items that are valid' do
Should be "populates and indexes". 

It's a symptom of a spec that's testing too many things, but unfortunately that's the case for a lot of our older specs. I'm going to create a ticket for one of the new folks to disable auto-correction for that cop, as it has tripped us up in various ways in the past.

See also https://github.com/rubocop/rubocop-rspec/issues/1179

2022-08-10 16:40 UTC, MothOnMars commented on spec/lib/importers/rss_feed_data_spec.rb
> +      it 'populates and index just the news items that are valid' do
Should be "populates and indexes"

2022-08-10 16:40 UTC, MothOnMars commented on spec/lib/importers/rss_feed_data_spec.rb
> +      it 'populates and index just the news items that are valid' do
Should be "populates and indexes"

2022-08-10 16:40 UTC, MothOnMars commented on spec/lib/importers/rss_feed_data_spec.rb
> +      it 'logs it and move on' do
Should be "logs it and moves on"

2022-08-10 16:40 UTC, MothOnMars commented on spec/lib/importers/rss_feed_data_spec.rb
> +      it 'does not change the number of news items, and update the crawl status' do
Should be "does not change the number of news items, and updates the crawl status"

2022-08-10 16:40 UTC, MothOnMars commented on spec/lib/tasks/twitter_spec.rb
> +        it 'onlies create a new tweet if the user id matches a TwitterProfile' do
Should be "only creates"

2022-08-10 17:02 UTC, lorawoodford commented
@MothOnMars Requested changes made.

2022-08-10 17:46 UTC, MothOnMars submitted a review, later dismissed
LGTM

2022-09-06 16:46 UTC, MothOnMars commented
SRCH-3206 has been closed as done. Additional changes will be made to this PR to support a "safe" migration via https://cm-jira.usa.gov/browse/SRCH-3345, which will also cover the deployment of these changes.

2023-01-06 20:17 UTC, MothOnMars commented
Closing this up. I'm tweaking these changes for SRCH-3345 and breaking this into smaller chunks to simplify testing & deployment.

2023-01-06 20:17 UTC, closed without merging